### ISSUE TITLE
read.beast function not working

### ISSUE THREAD

**Issue by avvypaks** [fmichonneau/phyloch#2]
I am trying to read my Tree annotator output .tre file through this package. But it appears to me that the function is missing, Can you suggest me any other package to perform this task ?

**Comment by fmichonneau** [comment]
I'm not following phylogenetics software that closely these days, but maybe you'll find useful info in this blog post: https://ropensci.org/blog/2020/01/28/babette/ 
I'm not phyloch author, I just put the code on GitHub as I needed for my scripts.
